-- MySQL Script generated by MySQL Workbench
-- 07/23/17 13:58:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProyectoPhP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoPhP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoPhP` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ProyectoPhP` ;

-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Secretarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Secretarias` (
  `idSecretarias` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Vision` TEXT NOT NULL,
  `Mision` TEXT NOT NULL,
  `Objetivos` TEXT NOT NULL,
  `Telefono` BIGINT(20) NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idSecretarias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Persona` (
  `idPersona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Tipo_Documento` ENUM('C.C', 'T.I', 'R.C', 'C.E', 'Otros') NOT NULL,
  `Documento` BIGINT(20) UNSIGNED NOT NULL,
  `Foto` VARCHAR(200) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Genero` ENUM('Masculino', 'Femenino') NOT NULL,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Telefono` BIGINT(20) UNSIGNED NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  `Correo` VARCHAR(60) NOT NULL,
  `Contrato_PDF` VARCHAR(200) NULL,
  `NRP` INT UNSIGNED NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contrasena` VARCHAR(255) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `Cargo` VARCHAR(45) NOT NULL,
  `idSecretarias` INT UNSIGNED NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC),
  INDEX `fk_Persona_Secretarias1_idx` (`idSecretarias` ASC),
  CONSTRAINT `fk_Persona_Secretarias1`
    FOREIGN KEY (`idSecretarias`)
    REFERENCES `ProyectoPhP`.`Secretarias` (`idSecretarias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Contatos_Publicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Contatos_Publicos` (
  `idContatos_Publicos` INT NOT NULL AUTO_INCREMENT,
  `Tipo_Proceso` VARCHAR(45) NOT NULL,
  `Estado` ENUM('Cancelado', 'En ejecucion', 'Liquidado') NOT NULL,
  `RC` VARCHAR(45) NOT NULL,
  `Descripcion_Objeto_Contratar` VARCHAR(45) NOT NULL,
  `Cuantia` VARCHAR(45) NOT NULL,
  `Tipo_Contrato` VARCHAR(45) NOT NULL,
  `departamento_Ejecucion` VARCHAR(45) NOT NULL,
  `municipio_ejecucion` VARCHAR(45) NOT NULL,
  `Departamento_Obtenciondocumentos` VARCHAR(45) NOT NULL,
  `Municipio_Obtencion_Documentos` VARCHAR(45) NOT NULL,
  `Direccion_Entrega_Documentos` VARCHAR(45) NOT NULL,
  `Fecha_Hora_Apertura_Proceso` VARCHAR(45) NOT NULL,
  `idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idContatos_Publicos`),
  INDEX `fk_Contatos_Publicos_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Contatos_Publicos_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `ProyectoPhP`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Empresas` (
  `idEmpresas` INT NOT NULL AUTO_INCREMENT,
  `Razonsocial_contratista` VARCHAR(45) NOT NULL,
  `Identificacion_Contatista` VARCHAR(45) NOT NULL,
  `Pais_Contatrista` VARCHAR(45) NOT NULL,
  `Departamento_Contatista` VARCHAR(45) NOT NULL,
  `Provincia_Contratista` VARCHAR(45) NOT NULL,
  `Direccion_Contratista` VARCHAR(45) NOT NULL,
  `Representante_Contaratista` VARCHAR(45) NOT NULL,
  `Identificacion_Representante` VARCHAR(45) NOT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  `idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEmpresas`),
  INDEX `fk_Empresas_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Empresas_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `ProyectoPhP`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Licitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Licitacion` (
  `idLicitacion` INT NOT NULL AUTO_INCREMENT,
  `Fecha_firma_contrato` DATE NOT NULL,
  `Ejecucion_Contrato` VARCHAR(45) NOT NULL,
  `Plazo_Ejecucion_Contrato` VARCHAR(45) NOT NULL,
  `Calificacion` VARCHAR(45) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `idPersona` INT UNSIGNED NOT NULL,
  `idEmpresas` INT NOT NULL,
  `idContatos_Publicos` INT NOT NULL,
  PRIMARY KEY (`idLicitacion`),
  INDEX `fk_Liquidacion_Contrato_Persona1_idx` (`idPersona` ASC),
  INDEX `fk_Licitacion_Empresas1_idx` (`idEmpresas` ASC),
  INDEX `fk_Licitacion_Contatos_Publicos1_idx` (`idContatos_Publicos` ASC),
  CONSTRAINT `fk_Liquidacion_Contrato_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `ProyectoPhP`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Licitacion_Empresas1`
    FOREIGN KEY (`idEmpresas`)
    REFERENCES `ProyectoPhP`.`Empresas` (`idEmpresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Licitacion_Contatos_Publicos1`
    FOREIGN KEY (`idContatos_Publicos`)
    REFERENCES `ProyectoPhP`.`Contatos_Publicos` (`idContatos_Publicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Documentos` (
  `idDocumentos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Version` VARCHAR(45) NOT NULL,
  `Fecha_Publicacion` DATE NOT NULL,
  `idContatos_Publicos` INT NULL,
  `idEmpresas` INT NULL,
  `idLiquidacion_Contrato` INT NULL,
  PRIMARY KEY (`idDocumentos`),
  INDEX `fk_Documentos_Contatos_Publicos1_idx` (`idContatos_Publicos` ASC),
  INDEX `fk_Documentos_Empresas1_idx` (`idEmpresas` ASC),
  INDEX `fk_Documentos_Liquidacion_Contrato1_idx` (`idLiquidacion_Contrato` ASC),
  CONSTRAINT `fk_Documentos_Contatos_Publicos1`
    FOREIGN KEY (`idContatos_Publicos`)
    REFERENCES `ProyectoPhP`.`Contatos_Publicos` (`idContatos_Publicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documentos_Empresas1`
    FOREIGN KEY (`idEmpresas`)
    REFERENCES `ProyectoPhP`.`Empresas` (`idEmpresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documentos_Liquidacion_Contrato1`
    FOREIGN KEY (`idLiquidacion_Contrato`)
    REFERENCES `ProyectoPhP`.`Licitacion` (`idLicitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Registro_Actas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Registro_Actas` (
  `idRegistro_Actas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Fecha_Hora` DATETIME NOT NULL,
  `Lugar_Reunion` VARCHAR(45) NOT NULL,
  `Lista_Asistencia` VARCHAR(45) NOT NULL,
  `Puntos_Tratados` VARCHAR(45) NOT NULL,
  `Acuerdos_Tomados` VARCHAR(45) NOT NULL,
  `Observaciones` VARCHAR(45) NOT NULL,
  `Direccion_Reunion` VARCHAR(45) NOT NULL,
  `idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRegistro_Actas`),
  INDEX `fk_Registro_Actas_Persona1_idx` (`idPersona` ASC),
  CONSTRAINT `fk_Registro_Actas_Persona1`
    FOREIGN KEY (`idPersona`)
    REFERENCES `ProyectoPhP`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Entregables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Entregables` (
  `idEntregables` INT NOT NULL,
  `Entregables_Actividad` VARCHAR(45) NOT NULL,
  `Fecha_Cumplimiento` DATETIME NOT NULL,
  `Fecha_Entrega` DATETIME NOT NULL,
  `Porcentaje_Entregable` SMALLINT NOT NULL,
  `Contrato` INT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NULL,
  `idLiquidacion_Contrato` INT NOT NULL,
  PRIMARY KEY (`idEntregables`),
  INDEX `fk_Registro_Cumplimientos_Liquidacion_Contrato1_idx` (`idLiquidacion_Contrato` ASC),
  CONSTRAINT `fk_Registro_Cumplimientos_Liquidacion_Contrato1`
    FOREIGN KEY (`idLiquidacion_Contrato`)
    REFERENCES `ProyectoPhP`.`Licitacion` (`idLicitacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Certificados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Certificados` (
  `idCertificados` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Dependencia` VARCHAR(45) NOT NULL,
  `N_Acta` INT NOT NULL,
  `FechaHora_Recibido` DATETIME NOT NULL,
  `Empresa` VARCHAR(45) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `Contrato` VARCHAR(45) NOT NULL,
  `idEntregables` INT NOT NULL,
  PRIMARY KEY (`idCertificados`),
  INDEX `fk_Certificados_Entregables1_idx` (`idEntregables` ASC),
  CONSTRAINT `fk_Certificados_Entregables1`
    FOREIGN KEY (`idEntregables`)
    REFERENCES `ProyectoPhP`.`Entregables` (`idEntregables`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
