-- MySQL Script generated by MySQL Workbench
-- Fri Jul  7 18:32:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ProyectoPhP
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ProyectoPhP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ProyectoPhP` DEFAULT CHARACTER SET utf8 ;
USE `ProyectoPhP` ;

-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Secretarias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Secretarias` (
  `idSecretarias` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Vision` TEXT NOT NULL,
  `Mision` TEXT NOT NULL,
  `Objetivos` TEXT NOT NULL,
  `Telefono` BIGINT(20) NOT NULL,
  `Direccion` VARCHAR(45) NULL,
  PRIMARY KEY (`idSecretarias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Persona` (
  `idPersona` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Tipo_Documento` ENUM('C.C', 'T.I', 'R.C', 'C.E', 'Otros') NOT NULL,
  `Documento` BIGINT(20) UNSIGNED NOT NULL,
  `Foto` VARCHAR(50) NOT NULL,
  `Fecha_Nacimiento` DATE NOT NULL,
  `Genero` ENUM('Masculino', 'Femenino') NOT NULL,
  `Nombres` VARCHAR(50) NOT NULL,
  `Apellidos` VARCHAR(50) NOT NULL,
  `Telefono` BIGINT(20) UNSIGNED NOT NULL,
  `Direccion` VARCHAR(60) NOT NULL,
  `Correo` VARCHAR(60) NOT NULL,
  `Contrato_PDF` VARCHAR(50) NULL,
  `NRP` INT UNSIGNED NULL,
  `Usuario` VARCHAR(45) NOT NULL,
  `Contrasena` VARCHAR(45) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `Cargo` ENUM('General', 'Subgeneral', 'Secretari@', 'Administrador') NOT NULL,
  `Secretarias_idSecretarias` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPersona`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC),
  INDEX `fk_Persona_Secretarias1_idx` (`Secretarias_idSecretarias` ASC),
  CONSTRAINT `fk_Persona_Secretarias1`
    FOREIGN KEY (`Secretarias_idSecretarias`)
    REFERENCES `ProyectoPhP`.`Secretarias` (`idSecretarias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Contatos_Publicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Contatos_Publicos` (
  `idContatos_Publicos` INT NOT NULL AUTO_INCREMENT,
  `Estado` ENUM('Cancelado', 'En ejecucion', 'Liquidado') NOT NULL,
  `RC` VARCHAR(45) NOT NULL,
  `Grupo` VARCHAR(45) NOT NULL,
  `Segmento` VARCHAR(45) NOT NULL,
  `Familia` VARCHAR(45) NOT NULL,
  `Clase` VARCHAR(45) NOT NULL,
  `Detalle` VARCHAR(45) NOT NULL,
  `Capital_Contratar` VARCHAR(45) NOT NULL,
  `Tipo_Contato` VARCHAR(45) NOT NULL,
  `Novedades` VARCHAR(45) NOT NULL,
  `Tipo_Respaldo` VARCHAR(45) NOT NULL,
  `NRP` VARCHAR(45) NOT NULL,
  `CRP` VARCHAR(45) NOT NULL,
  `DME` VARCHAR(45) NOT NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idContatos_Publicos`),
  INDEX `fk_Contatos_Publicos_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Contatos_Publicos_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ProyectoPhP`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Empresas` (
  `idEmpresas` INT NOT NULL AUTO_INCREMENT,
  `NRC` VARCHAR(45) NOT NULL,
  `Identificacion_Contatista` VARCHAR(45) NOT NULL,
  `Pais_Contatrista` VARCHAR(45) NOT NULL,
  `Departamento_Contatista` VARCHAR(45) NOT NULL,
  `Provincia_Contratista` VARCHAR(45) NOT NULL,
  `Direccion_Contratista` VARCHAR(45) NOT NULL,
  `RLC` VARCHAR(45) NOT NULL,
  `Identificacion_Representante` VARCHAR(45) NOT NULL,
  `Calificacion` VARCHAR(45) NOT NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idEmpresas`),
  INDEX `fk_Empresas_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Empresas_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ProyectoPhP`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Liquidacion_Contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Liquidacion_Contrato` (
  `idLiquidacion_Contrato` INT NOT NULL AUTO_INCREMENT,
  `Departamento_Ejecucion` VARCHAR(45) NOT NULL,
  `Municipuo_Ejecucion` VARCHAR(45) NOT NULL,
  `DOD` VARCHAR(45) NOT NULL,
  `MOD` VARCHAR(45) NOT NULL,
  `Direccion_OD` VARCHAR(45) NOT NULL,
  `Departmento_ED` VARCHAR(45) NOT NULL,
  `Municipio_ED` VARCHAR(45) NOT NULL,
  `Fecha_Hora_Apertura` DATETIME NOT NULL,
  `Fecha_Hora_Audencia` DATETIME NOT NULL,
  `Lugar_Audencia` VARCHAR(45) NOT NULL,
  `Fecha_Hora_Cierre` DATETIME NOT NULL,
  `Fecha_Hora_AudienciaAdjudicación` DATETIME NOT NULL,
  `Lugar_Audiencia_Adjudicacion` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Ubicacion_Sala_Consulta` VARCHAR(45) NOT NULL,
  `Calificacion_Definitiva` VARCHAR(45) NULL,
  `NRSRS` VARCHAR(45) NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idLiquidacion_Contrato`),
  INDEX `fk_Liquidacion_Contrato_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Liquidacion_Contrato_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ProyectoPhP`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Documentos` (
  `idDocumentos` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Tamaño` VARCHAR(45) NOT NULL,
  `Version` VARCHAR(45) NOT NULL,
  `Fecha_Publicacion` DATE NOT NULL,
  `Contatos_Publicos_idContatos_Publicos` INT NULL,
  `Empresas_idEmpresas` INT NULL,
  `Liquidacion_Contrato_idLiquidacion_Contrato` INT NULL,
  PRIMARY KEY (`idDocumentos`),
  INDEX `fk_Documentos_Contatos_Publicos1_idx` (`Contatos_Publicos_idContatos_Publicos` ASC),
  INDEX `fk_Documentos_Empresas1_idx` (`Empresas_idEmpresas` ASC),
  INDEX `fk_Documentos_Liquidacion_Contrato1_idx` (`Liquidacion_Contrato_idLiquidacion_Contrato` ASC),
  CONSTRAINT `fk_Documentos_Contatos_Publicos1`
    FOREIGN KEY (`Contatos_Publicos_idContatos_Publicos`)
    REFERENCES `ProyectoPhP`.`Contatos_Publicos` (`idContatos_Publicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documentos_Empresas1`
    FOREIGN KEY (`Empresas_idEmpresas`)
    REFERENCES `ProyectoPhP`.`Empresas` (`idEmpresas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Documentos_Liquidacion_Contrato1`
    FOREIGN KEY (`Liquidacion_Contrato_idLiquidacion_Contrato`)
    REFERENCES `ProyectoPhP`.`Liquidacion_Contrato` (`idLiquidacion_Contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Historial` (
  `idHistorial` INT NOT NULL,
  `Celebracion_Contrato` DATETIME NOT NULL,
  `Creacion_Proceso` DATETIME NOT NULL,
  `Liquidacion_Contrato_idLiquidacion_Contrato` INT NOT NULL,
  `Contatos_Publicos_idContatos_Publicos` INT NOT NULL,
  PRIMARY KEY (`idHistorial`),
  INDEX `fk_Historial_Liquidacion_Contrato1_idx` (`Liquidacion_Contrato_idLiquidacion_Contrato` ASC),
  INDEX `fk_Historial_Contatos_Publicos1_idx` (`Contatos_Publicos_idContatos_Publicos` ASC),
  CONSTRAINT `fk_Historial_Liquidacion_Contrato1`
    FOREIGN KEY (`Liquidacion_Contrato_idLiquidacion_Contrato`)
    REFERENCES `ProyectoPhP`.`Liquidacion_Contrato` (`idLiquidacion_Contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Historial_Contatos_Publicos1`
    FOREIGN KEY (`Contatos_Publicos_idContatos_Publicos`)
    REFERENCES `ProyectoPhP`.`Contatos_Publicos` (`idContatos_Publicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Registro_Actas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Registro_Actas` (
  `idRegistro_Actas` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Fecha_Hora` DATETIME NOT NULL,
  `Lugar_Reunion` VARCHAR(45) NOT NULL,
  `Lista_Asistencia` VARCHAR(45) NOT NULL,
  `Puntos_Tratados` VARCHAR(45) NOT NULL,
  `Acuerdos_Tomados` VARCHAR(45) NOT NULL,
  `Observaciones` VARCHAR(45) NOT NULL,
  `Direccion_Reunion` VARCHAR(45) NOT NULL,
  `Persona_idPersona` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idRegistro_Actas`),
  INDEX `fk_Registro_Actas_Persona1_idx` (`Persona_idPersona` ASC),
  CONSTRAINT `fk_Registro_Actas_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `ProyectoPhP`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Registro_Cumplimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Registro_Cumplimientos` (
  `idRegistro_Cumplimientos` INT NOT NULL,
  `Entregables_Actividad` VARCHAR(45) NOT NULL,
  `Fecha_Cumplimiento` DATETIME NOT NULL,
  `Fecha_Entrega` DATETIME NOT NULL,
  `Porcentaje_Entregable` SMALLINT NOT NULL,
  `Liquidacion_Contrato_idLiquidacion_Contrato` INT NOT NULL,
  PRIMARY KEY (`idRegistro_Cumplimientos`),
  INDEX `fk_Registro_Cumplimientos_Liquidacion_Contrato1_idx` (`Liquidacion_Contrato_idLiquidacion_Contrato` ASC),
  CONSTRAINT `fk_Registro_Cumplimientos_Liquidacion_Contrato1`
    FOREIGN KEY (`Liquidacion_Contrato_idLiquidacion_Contrato`)
    REFERENCES `ProyectoPhP`.`Liquidacion_Contrato` (`idLiquidacion_Contrato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ProyectoPhP`.`Registro_Certificados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ProyectoPhP`.`Registro_Certificados` (
  `idRegistro_Certificados` INT NOT NULL,
  `Fecha` DATE NOT NULL,
  `Dependencia` VARCHAR(45) NOT NULL,
  `N_Acta` INT NOT NULL,
  `FechaHora_Recibido` DATETIME NOT NULL,
  `Nombre_Contratista` VARCHAR(45) NOT NULL,
  `Nombre_Registrador` VARCHAR(45) NOT NULL,
  `ActaPDF` VARCHAR(45) NOT NULL,
  `Registro_Cumplimientos_idRegistro_Cumplimientos` INT NOT NULL,
  PRIMARY KEY (`idRegistro_Certificados`),
  INDEX `fk_Registro_Certificados_Registro_Cumplimientos1_idx` (`Registro_Cumplimientos_idRegistro_Cumplimientos` ASC),
  CONSTRAINT `fk_Registro_Certificados_Registro_Cumplimientos1`
    FOREIGN KEY (`Registro_Cumplimientos_idRegistro_Cumplimientos`)
    REFERENCES `ProyectoPhP`.`Registro_Cumplimientos` (`idRegistro_Cumplimientos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
